version: "2"

linters:
  enable:
    - bidichk
    - errcheck
    - gocritic
    - exhaustive
    - exhaustruct
    - exptostd
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecknoglobals
    - govet
    - ineffassign
    - misspell
    - nlreturn
    - paralleltest
    - prealloc
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - usetesting
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    exhaustruct:
      exclude:
        - 'github\.com/krzysztofgb/jfmt\.Options'
        - 'github\.com/krzysztofgb/jfmt\.fixer'

formatters:
  enable:
    - gci
    - gofumpt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - exhaustruct
        - gochecknoglobals
