version: 2

builds:
  - main: ./cmd/jfmt
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

binary_signs:
  - {}

homebrew_casks:
  - name: jfmt
    repository:
      owner: krzysztofgb
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/krzysztofgb/jfmt
    description: A JSON formatter and validator for the command line.
    license: Unlicense
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jfmt"]
          end

changelog:
  use: github
  abbrev: -1
  format: "{{.Message}} (@{{.AuthorUsername}})"
  sort: asc
  groups:
    - title: New Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+'
      order: 2
    - title: Refactoring
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+'
      order: 3
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+'
      order: 4
    - title: Other
      order: 999
  filters:
    exclude: []
