version: 2

builds:
  - main: ./cmd/jfmt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

changelog:
  use: github
  sort: asc
  abbrev: -1
  groups:
    - title: New Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+'
      order: 2
    - title: Refactoring
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+'
      order: 3
    - title: Dependency Updates
      regexp: '^.*?deps(\([[:word:]]+\))??!?:.+'
      order: 4
    - title: Other
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^build:"
