on: [pull_request]
jobs:
  run-linters:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Tools
        uses: jdx/mise-action@v4

      - name: Lint Code
        run: task lint

  run-tests:
    name: Run Tests
    uses: ./.github/workflows/test.yml
