on:
  workflow_call:
jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.24.x
          - 1.25.x
          - 1.26.x
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Tools
        uses: jdx/mise-action@v4

      - name: Test
        run: task test

  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Tools
        uses: jdx/mise-action@v4

      - name: Fuzz
        run: task fuzz FUZZTIME=10s
